### ISSUE TITLE
Módulo 3.4 Asignación

### ISSUE THREAD

**Issue by Rosalba2023** [SistemasTecTlaxiaco/rose#14]
LInk: https://classroom.github.com/a/ka2AT4LW

<img width="927" alt="image" src="https://github.com/SistemasTecTlaxiaco/rose/assets/137822092/6b7dd9b5-f629-4ec2-9c8c-b27272ad1299">

**Comment by josealfredo79** [comment]
Muy bien maestra...gracias...
